import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MediQueue",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} >
      <body className= {`theme === "dark" ? "bg-gray-900 text-white" : "bg-white text-black`}>
        <div className="flex">
          <div className="fixed left-0 top-0 h-screen w-9.5 z-50">
            <Image src="/assets/ruler.png" alt="ruler"  width={100} height={500} className="h-screen w-full object-cover" priority />
          </div>
          <div className="ml-10 w-full flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-1">{children}
              <Toaster position="top-center" />
            </main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
